### ISSUE TITLE
Cannot get compiled Kernel to boot

### ISSUE THREAD

**Issue by mKenfenheuer** [realme-kernel-opensource/realmeX2Pro-kernel-source#4]
I am able to compile the Kernel but with the repacked boot image including the compiled kernel i am not able to boot. It just goes straight to fastboot again.

**Comment by GT020** [comment]
> I am able to compile the Kernel but with the repacked boot image including the compiled kernel i am not able to boot. It just goes straight to fastboot again.

Internal project number of realme x2 pro is MSM_19781 try building using this.

**Comment by Sushantdk123** [comment]
No

**Comment by mKenfenheuer** [comment]
To be more precise: i have created a repo with all my build tools used: 

https://github.com/mKenfenheuer/realme-X2Pro-kernel-build

What am i missing?
